version: "3"

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: ./production/php
      dockerfile: app.Dockerfile
      args:
        user: new-user
        uid: 1000
    image: agriculture
    container_name: agriculture
    working_dir: /app
    links:
      - mariadb
      - mongodb
    volumes:
      - ./:/app
    networks:
      - app-network

  mariadb:
    image: mariadb
    container_name: "agriculture_database"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  mongodb:
    image: mongo:3.6
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/mongo:/data/db
    networks: 
      - app-network

  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    ports:
      - 9001:80
    links:
      - app
    volumes:
      - ./:/app
      - ./production/nginx:/etc/nginx/conf.d
    networks:
      - app-network

