version: "3"

networks:
  app-network:
    driver: bridge

services: 
  app:
    build: 
      context: ./production/php
      dockerfile: app.Dockerfile
      args: 
        user: new-user
        uid: 1000
    image: agriculture
    container_name: agriculture
    restart: unless-stopped
    working_dir: /app
    links: 
      - mariadb
    volumes:
      - ./:/app
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - mariadb
    ports:
        - 8082:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  mariadb:
    image: mariadb
    container_name: 'agriculture_database'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    links: 
      - app
    volumes:
      - ./:/app
      - ./production/nginx:/etc/nginx/conf.d
    networks:
      - app-network
  
  composer:
    image: composer
    restart: 'no'
    command: install
    volumes: 
      - .:/app
    networks: 
      - app-network


